version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ message broker port
      - "15672:15672" # Management web UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    networks:
      # defined a network for better isolation
      - rabbitmq_net

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-dev
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
    # environment: # - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    ports:
      - "3005:3005"
    networks:
      - rabbitmq_net # <-- To explicitly join the network
    command: [ "npm", "run", "start:dev" ]

# volumes:
#   rabbitmq_data:


networks:
  rabbitmq_net:
    driver: bridge
