version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq_host
    ports:
      - "5672:5672" # RabbitMQ message broker port
      - "15672:15672" # Management web UI port
      # environment:
      # RABBITMQ_DEFAULT_USER: admin
      # RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      # ⚠️ BIND MOUNT THE CONFIGURATION FILES ⚠️
      - ./etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./etc/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - rabbitmq_net # defined a network for better isolation

  nestjs:
    # build:
    #   target: development
    image: nestjs-api-image-dev:latest #Assigns name to the resulting image
    container_name: nestjs-dev
    depends_on:
      - rabbitmq
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # environment: 
    #   RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    # ports:
    #   - "3005:3005"
    networks:
      - rabbitmq_net # <-- To explicitly join the network
    # command: [ "npm", "run", "start:dev" ]

volumes:
  rabbitmq_data:
    #to add users and survive container and image deletion, but only keeping naming as it is


networks:
  rabbitmq_net:
    driver: bridge

# to run: 
#   docker-compose up {add a service name to only run it}
#   to run with image build: docker-compose up --build
#   find the api in browser at: http://127.0.0.1:3005/swagger

# run dev containers
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d && docker-compose logs -f nestjs

# run prod containers
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d && docker-compose logs -f nestjs --tail
