version: '3.8'

services:
  nestjs:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents local node_modules from overwriting container's
    ports:
      - "3005:3005"
    command: [ "npm", "run", "start:dev" ]
    # environment:
    #   NODE_ENV: development
